import {
  Stethoscope,
  Activity,
  Heart,
  Brain,
  Bone,
  Baby,
  HeartPulse,
  Eye,
  Fingerprint,
  Droplet,
  SmilePlus,
  ClipboardList,
  ClipboardCheck,
  Pill,
  FileText,
  ShieldCheck,
  Share2,
  Video,
  FlaskConical,
  Building,
  Calculator,
  Clock,
  LayoutDashboard,
  ShieldAlert,
  Scan,
  Scissors,
  Calendar,
  TrendingUp,
  Bell,
  Layers,
  ListOrdered,
  AlertTriangle,
  Monitor,
  Zap,
  Watch,
  Shield,
  BookOpen,
  Link,
  Camera,
  Search,
  Sun,
  MapPin,
  SplitSquareVertical,
  Lock,
  Circle,
  Grid3X3,
  Thermometer,
  Microscope,
  User,
  Users,
  Coffee,
  DollarSign,
  Syringe,
  Diamond,
  Gauge,
  Dumbbell,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const specialtyIconMap: Record<string, LucideIcon> = {
  Stethoscope,
  Activity,
  Heart,
  Brain,
  Bone,
  Baby,
  HeartPulse,
  Eye,
  Fingerprint,
  Droplet,
  SmilePlus,
  ClipboardList,
  ClipboardCheck,
  Pill,
  FileText,
  ShieldCheck,
  Share2,
  Video,
  FlaskConical,
  Building,
  Calculator,
  Clock,
  LayoutDashboard,
  ShieldAlert,
  Scan,
  Scissors,
  Calendar,
  TrendingUp,
  Bell,
  Layers,
  ListOrdered,
  AlertTriangle,
  Monitor,
  Zap,
  Watch,
  Shield,
  BookOpen,
  Link,
  Camera,
  Search,
  Sun,
  MapPin,
  SplitSquareVertical,
  Lock,
  Circle,
  Grid3x3: Grid3X3,
  Grid3X3,
  Thermometer,
  Microscope,
  User,
  Users,
  Coffee,
  DollarSign,
  Syringe,
  Diamond,
  Gauge,
  Dumbbell,
};

export const colorConfig: Record<
  string,
  {
    gradient: string;
    bgLight: string;
    text: string;
    border: string;
    pill: string;
    ring: string;
    gradientFrom: string;
    gradientTo: string;
  }
> = {
  blue: {
    gradient: 'from-blue-950/60 via-zinc-950 to-blue-950/40',
    bgLight: 'bg-blue-500/10',
    text: 'text-blue-400',
    border: 'border-blue-500/20',
    pill: 'bg-blue-500/15 text-blue-300',
    ring: 'ring-blue-500/30',
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-blue-400',
  },
  red: {
    gradient: 'from-red-950/60 via-zinc-950 to-red-950/40',
    bgLight: 'bg-red-500/10',
    text: 'text-red-400',
    border: 'border-red-500/20',
    pill: 'bg-red-500/15 text-red-300',
    ring: 'ring-red-500/30',
    gradientFrom: 'from-red-500',
    gradientTo: 'to-red-400',
  },
  purple: {
    gradient: 'from-purple-950/60 via-zinc-950 to-purple-950/40',
    bgLight: 'bg-purple-500/10',
    text: 'text-purple-400',
    border: 'border-purple-500/20',
    pill: 'bg-purple-500/15 text-purple-300',
    ring: 'ring-purple-500/30',
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-purple-400',
  },
  orange: {
    gradient: 'from-orange-950/60 via-zinc-950 to-orange-950/40',
    bgLight: 'bg-orange-500/10',
    text: 'text-orange-400',
    border: 'border-orange-500/20',
    pill: 'bg-orange-500/15 text-orange-300',
    ring: 'ring-orange-500/30',
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-orange-400',
  },
  sky: {
    gradient: 'from-sky-950/60 via-zinc-950 to-sky-950/40',
    bgLight: 'bg-sky-500/10',
    text: 'text-sky-400',
    border: 'border-sky-500/20',
    pill: 'bg-sky-500/15 text-sky-300',
    ring: 'ring-sky-500/30',
    gradientFrom: 'from-sky-500',
    gradientTo: 'to-sky-400',
  },
  pink: {
    gradient: 'from-pink-950/60 via-zinc-950 to-pink-950/40',
    bgLight: 'bg-pink-500/10',
    text: 'text-pink-400',
    border: 'border-pink-500/20',
    pill: 'bg-pink-500/15 text-pink-300',
    ring: 'ring-pink-500/30',
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-pink-400',
  },
  cyan: {
    gradient: 'from-cyan-950/60 via-zinc-950 to-cyan-950/40',
    bgLight: 'bg-cyan-500/10',
    text: 'text-cyan-400',
    border: 'border-cyan-500/20',
    pill: 'bg-cyan-500/15 text-cyan-300',
    ring: 'ring-cyan-500/30',
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-cyan-400',
  },
  teal: {
    gradient: 'from-teal-950/60 via-zinc-950 to-teal-950/40',
    bgLight: 'bg-teal-500/10',
    text: 'text-teal-400',
    border: 'border-teal-500/20',
    pill: 'bg-teal-500/15 text-teal-300',
    ring: 'ring-teal-500/30',
    gradientFrom: 'from-teal-500',
    gradientTo: 'to-teal-400',
  },
  violet: {
    gradient: 'from-violet-950/60 via-zinc-950 to-violet-950/40',
    bgLight: 'bg-violet-500/10',
    text: 'text-violet-400',
    border: 'border-violet-500/20',
    pill: 'bg-violet-500/15 text-violet-300',
    ring: 'ring-violet-500/30',
    gradientFrom: 'from-violet-500',
    gradientTo: 'to-violet-400',
  },
};

export function getColors(accentColor: string) {
  return colorConfig[accentColor] ?? colorConfig.teal;
}

export function getIcon(iconName: string) {
  return specialtyIconMap[iconName] ?? Stethoscope;
}
