"use client";

import { type LucideProps } from "lucide-react";
import {
    Activity,
    AlignCenter,
    AlertTriangle,
    Apple,
    Atom,
    Baby,
    Bone,
    BookOpen,
    Box,
    Brain,
    BrainCircuit,
    BrainCog,
    Calendar,
    CheckSquare,
    ClipboardList,
    CreditCard,
    Dna,
    DollarSign,
    Droplet,
    Droplets,
    Dumbbell,
    Ear,
    Eye,
    FileText,
    Fingerprint,
    Flame,
    FlaskConical,
    Flower2,
    Focus,
    Footprints,
    Gauge,
    GitBranch,
    Glasses,
    Hand,
    HardHat,
    Heart,
    HeartHandshake,
    HeartPulse,
    MessageCircle,
    MessageSquare,
    Mic,
    Microscope,
    Moon,
    Package,
    Phone,
    Pill,
    Puzzle,
    Radiation,
    Radio,
    Receipt,
    Ribbon,
    Scale,
    Scan,
    ScanLine,
    Scissors,
    Search,
    Settings,
    Shield,
    ShieldAlert,
    ShieldCheck,
    Siren,
    Skull,
    SmilePlus,
    Sparkle,
    Sparkles,
    Stethoscope,
    Syringe,
    Target,
    TrendingUp,
    User,
    Users,
    Utensils,
    Video,
    Volume2,
    Waves,
    Wind,
    Zap,
} from "lucide-react";
import type { ComponentType } from "react";

const ICON_MAP: Record<string, ComponentType<LucideProps>> = {
    Activity,
    AlignCenter,
    AlertTriangle,
    Apple,
    Atom,
    Baby,
    Bone,
    BookOpen,
    Box,
    Brain,
    BrainCircuit,
    BrainCog,
    Calendar,
    CheckSquare,
    ClipboardList,
    CreditCard,
    Dna,
    DollarSign,
    Droplet,
    Droplets,
    Dumbbell,
    Ear,
    Eye,
    FileText,
    FileTemplate: FileText,
    Fingerprint,
    Flame,
    FlaskConical,
    Flower2,
    Focus,
    Footprints,
    Gauge,
    GitBranch,
    Glasses,
    Gum: SmilePlus,
    Hand,
    HandMetal: Hand,
    HardHat,
    Heart,
    HeartHandshake,
    HeartPulse,
    MessageCircle,
    MessageSquare,
    Mic,
    Microscope,
    Moon,
    Package,
    Phone,
    Pill,
    Puzzle,
    Radiation,
    Radio,
    Receipt,
    Ribbon,
    Scale,
    Scan,
    ScanLine,
    Scissors,
    Search,
    Settings,
    Shield,
    ShieldAlert,
    ShieldCheck,
    Siren,
    Skull,
    SmilePlus,
    Sparkle,
    Sparkles,
    Stethoscope,
    Syringe,
    Target,
    TrendingUp,
    User,
    Users,
    Utensils,
    Video,
    Volume2,
    Waves,
    Wind,
    Zap,
};

export const AVAILABLE_ICONS = Object.keys(ICON_MAP);

const DEFAULT_ICON = Stethoscope;

export interface DynamicIconProps extends LucideProps {
    name: string;
}

export function DynamicIcon({ name, ...props }: DynamicIconProps) {
    const IconComponent = ICON_MAP[name] || DEFAULT_ICON;
    return <IconComponent {...props} />;
}

export function isValidIconName(name: string): boolean {
    return name in ICON_MAP;
}

export function getIconComponent(
    name: string
): ComponentType<LucideProps> | null {
    return ICON_MAP[name] || null;
}
