/**
 * Catálogo de preparaciones / cosas que traer comunes a citas médicas en LATAM.
 * Generado para autocompletar el campo de "preparación / qué traer" en la
 * app médica. Pattern consistente con reason-catalog.ts.
 *
 * Cobertura aproximada (array plano):
 *  - Ayunos (sólidos, líquidos, parciales, según estudio)
 *  - Preparación intestinal (laxantes, dieta, enemas)
 *  - Estudios previos a traer (laboratorio, imagenología, cardio, GI, gineco)
 *  - Documentación administrativa (seguros, identidad, vacunación, autorizaciones)
 *  - Medicamentos y recetas (lista, cajas, esquemas, suspensiones)
 *  - Acompañantes y transporte
 *  - Vestimenta y comodidad
 *  - Higiene corporal previa
 *  - Dieta y restricciones alimentarias
 *  - Equipo médico personal
 *  - Medidas y registros personales (signos vitales, bitácoras)
 *  - Muestras a llevar
 *  - Misceláneos prácticos
 *
 * Estructura: array plano por simplicidad. Si más adelante queremos filtrar
 * por especialidad/tipo de cita, se puede convertir a `Record<Category, string[]>`.
 */

export const PREPARATION_CATALOG: ReadonlyArray<string> = [
  // ===== Ayunos (~50) =====
  'Ayuno 2h',
  'Ayuno 3h',
  'Ayuno 4h',
  'Ayuno 6h',
  'Ayuno 8h',
  'Ayuno 10h',
  'Ayuno 12h',
  'Ayuno 14h',
  'Ayuno absoluto',
  'Ayuno solo de sólidos',
  'Ayuno solo de líquidos',
  'Ayuno nocturno',
  'Ayuno desde la medianoche',
  'Ayuno desde las 22:00 horas',
  'Ayuno desde las 20:00 horas',
  'Ayuno previo a anestesia',
  'Ayuno previo a anestesia general',
  'Ayuno previo a sedación',
  'Ayuno previo a colonoscopia',
  'Ayuno previo a endoscopia',
  'Ayuno previo a gastroscopia',
  'Ayuno previo a tomografía con contraste',
  'Ayuno previo a resonancia magnética con contraste',
  'Ayuno previo a perfil lipídico',
  'Ayuno previo a glicemia',
  'Ayuno previo a curva de tolerancia a la glucosa',
  'Ayuno previo a perfil hepático',
  'Ayuno previo a perfil tiroideo',
  'Ayuno previo a insulinemia',
  'Ayuno previo a ácido úrico',
  'Ayuno previo a urea y creatinina',
  'Ayuno previo a perfil renal',
  'Ayuno previo a cirugía',
  'Ayuno previo a cirugía menor',
  'Ayuno previo a cirugía mayor',
  'Ayuno previo a ecografía abdominal',
  'Ayuno previo a ecografía hepatobiliar',
  'Sin desayunar',
  'Sin almorzar',
  'Sin cenar la noche anterior',
  'Sin tomar líquidos 2h antes',
  'Sin tomar líquidos 4h antes',
  'Sin tomar líquidos 6h antes',
  'Sin tomar agua 2h antes',
  'Sin café por la mañana',
  'Sin café desde 24 horas antes',
  'Sin chicle ni caramelos en ayuno',
  'Permitido tomar agua hasta 2h antes',
  'Permitido tomar agua hasta 1h antes',
  'Permitido tragar saliva',

  // ===== Preparación intestinal (~30) =====
  'Dieta líquida 24h antes',
  'Dieta líquida clara 24h antes',
  'Dieta líquida 48h antes',
  'Toma de fosfato de sodio la noche anterior',
  'Enema previo',
  'Enema evacuante la noche anterior',
  'Enema evacuante la mañana del estudio',
  'Laxante la noche anterior',
  'Laxante salino la tarde anterior',
  'Solución evacuante de polietilenglicol',
  'Solución evacuante dividida en dos tomas',
  'Picosulfato de sodio según indicación',
  'Bisacodilo la noche anterior',
  'Dieta baja en residuos 3 días antes',
  'Dieta baja en residuos 5 días antes',
  'Dieta blanda sin fibra 48h antes',
  'Sin frutas con semillas 72h antes',
  'Sin verduras crudas 48h antes',
  'Sin granos enteros 72h antes',
  'Sin lácteos enteros la víspera de la colonoscopia',
  'Sin alimentos integrales 72h antes',
  'Suspender suplementos de hierro 7 días antes del estudio digestivo',
  'Suspender carbón activado 48h antes',
  'Aumentar consumo de líquidos claros la víspera',
  'Caldo desgrasado permitido la víspera',
  'Gelatina sin colorante permitida',
  'Té claro sin leche permitido',
  'Jugo colado sin pulpa permitido',
  'Sin alimentos rojos o morados 48h antes',
  'Confirmar evacuaciones claras antes del estudio',

  // ===== Estudios previos a traer — Laboratorio (~25) =====
  'Traer hemograma completo reciente',
  'Traer hematología completa',
  'Traer perfil bioquímico',
  'Traer química sanguínea',
  'Traer perfil lipídico',
  'Traer perfil tiroideo',
  'Traer glicemia en ayunas',
  'Traer HbA1c',
  'Traer hemoglobina glicosilada',
  'Traer perfil hepático',
  'Traer perfil renal',
  'Traer pruebas de coagulación',
  'Traer urocultivo',
  'Traer urianálisis',
  'Traer examen general de orina',
  'Traer coprológico',
  'Traer coprocultivo',
  'Traer perfil hormonal',
  'Traer perfil 20',
  'Traer marcadores tumorales',
  'Traer prueba de embarazo',
  'Traer serología VIH',
  'Traer serología hepatitis B y C',
  'Traer VDRL',
  'Traer ferritina y hierro sérico',

  // ===== Estudios previos a traer — Imagenología (~50) =====
  'Traer ecografía abdominal previa',
  'Traer ecografía pélvica',
  'Traer ecografía transvaginal',
  'Traer ecografía obstétrica',
  'Traer ecografía obstétrica de primer trimestre',
  'Traer ecografía morfológica',
  'Traer ecografía mamaria',
  'Traer ecografía tiroidea',
  'Traer ecografía testicular',
  'Traer ecografía renal',
  'Traer ecografía hepatobiliar',
  'Traer ecografía Doppler de miembros inferiores',
  'Traer ecografía Doppler carotídeo',
  'Traer ecografía de partes blandas',
  'Traer radiografía de tórax',
  'Traer radiografía de tórax PA y lateral',
  'Traer radiografía de columna lumbar',
  'Traer radiografía de columna cervical',
  'Traer radiografía de columna dorsal',
  'Traer radiografía de rodilla',
  'Traer radiografía de rodilla en carga',
  'Traer radiografía de cadera',
  'Traer radiografía de hombro',
  'Traer radiografía de pie',
  'Traer radiografía de mano',
  'Traer radiografía de cráneo',
  'Traer radiografía panorámica dental',
  'Traer radiografía periapical',
  'Traer tomografía abdominal',
  'Traer tomografía abdomino-pélvica',
  'Traer tomografía cerebral',
  'Traer tomografía de cráneo simple',
  'Traer tomografía de tórax',
  'Traer tomografía de senos paranasales',
  'Traer tomografía de columna',
  'Traer tomografía con contraste',
  'Traer angiotomografía coronaria',
  'Traer resonancia magnética cerebral',
  'Traer resonancia de columna lumbar',
  'Traer resonancia de columna cervical',
  'Traer resonancia de rodilla',
  'Traer resonancia de hombro',
  'Traer resonancia de cadera',
  'Traer resonancia de tobillo',
  'Traer resonancia abdominal',
  'Traer urografía intravenosa',
  'Traer cistografía',
  'Traer estudio baritado de esófago',
  'Traer tránsito intestinal baritado',
  'Traer placas en CD o pendrive',

  // ===== Estudios previos a traer — Cardiología y GI (~30) =====
  'Traer electrocardiograma',
  'Traer electrocardiograma reciente',
  'Traer ecocardiograma',
  'Traer ecocardiograma Doppler',
  'Traer ecocardiograma transesofágico',
  'Traer holter de 24h',
  'Traer holter de 48h',
  'Traer holter de presión arterial',
  'Traer MAPA de 24h',
  'Traer prueba de esfuerzo',
  'Traer ergometría',
  'Traer perfusión miocárdica',
  'Traer cateterismo cardíaco previo',
  'Traer informe de marcapasos',
  'Traer endoscopia digestiva',
  'Traer endoscopia digestiva alta previa',
  'Traer colonoscopia previa',
  'Traer rectosigmoidoscopia',
  'Traer manometría esofágica',
  'Traer pH-metría esofágica',
  'Traer biopsia gástrica',
  'Traer biopsia intestinal',
  'Traer espirometría',
  'Traer prueba de función pulmonar',
  'Traer polisomnografía',
  'Traer estudio de sueño',
  'Traer electromiografía',
  'Traer electroencefalograma',
  'Traer potenciales evocados',
  'Traer Doppler transcraneal',

  // ===== Estudios previos a traer — Gineco/Uro/Otros (~25) =====
  'Traer mamografía',
  'Traer mamografía bilateral reciente',
  'Traer Papanicolau',
  'Traer citología cervicovaginal',
  'Traer colposcopia',
  'Traer biopsia cervical',
  'Traer histeroscopia',
  'Traer histerosalpingografía',
  'Traer espermograma',
  'Traer flujometría urinaria',
  'Traer cistoscopia previa',
  'Traer urodinamia',
  'Traer densitometría ósea',
  'Traer densitometría columna y cadera',
  'Traer estudios pendientes',
  'Traer estudios de los últimos 6 meses',
  'Traer estudios del último año',
  'Traer informe médico anterior',
  'Traer informe del especialista',
  'Traer historia clínica completa',
  'Traer resumen de historia clínica',
  'Traer biopsia previa',
  'Traer informe anatomopatológico',
  'Traer informe de citología',
  'Traer informe de patología',

  // ===== Documentación administrativa (~55) =====
  'Carnet del seguro',
  'Carnet del seguro vigente',
  'Carnet de afiliación',
  'Carnet de HCM',
  'Tarjeta del plan de salud',
  'Tarjeta de seguro privado',
  'Tarjeta de seguro corporativo',
  'Constancia de afiliación al seguro',
  'Cédula de identidad',
  'Cédula de identidad vigente',
  'Cédula del paciente',
  'Cédula del representante',
  'Cédula del menor',
  'Partida de nacimiento (menor de edad)',
  'Pasaporte (paciente extranjero)',
  'Pasaporte vigente',
  'Documento de identidad consular',
  'Carnet de vacunación',
  'Carnet de vacunación al día',
  'Cartilla de vacunación pediátrica',
  'Tarjeta de vacunación COVID',
  'Carnet prenatal',
  'Carnet de control prenatal',
  'Cartilla del bebé',
  'Cartilla CRED del niño',
  'Carnet de salud del adolescente',
  'Documento de autorización del seguro',
  'Carta aval del seguro',
  'Carta aval para procedimiento',
  'Clave de autorización del seguro',
  'Pre-autorización del seguro',
  'Constancia de cobertura',
  'Carta del médico tratante',
  'Carta de referencia del médico',
  'Referencia médica',
  'Hoja de remisión',
  'Hoja de interconsulta',
  'Orden médica firmada',
  'Orden de laboratorio',
  'Orden de estudios de imágenes',
  'Reposo médico previo',
  'Constancia de tratamiento previo',
  'Constancia de hospitalización previa',
  'Hoja de evolución hospitalaria',
  'Resumen de egreso hospitalario',
  'Epicrisis de hospitalización',
  'Historia clínica de hospitalización anterior',
  'Informe de quirófano',
  'Informe del anestesiólogo',
  'Consentimiento informado firmado',
  'Comprobante de pago de consulta',
  'Comprobante de pago de procedimiento',
  'Recibo de pago previo',
  'Factura electrónica de la consulta anterior',
  'Constancia laboral (certificados)',

  // ===== Medicamentos / recetas (~65) =====
  'Receta anterior',
  'Última receta médica',
  'Última receta del especialista',
  'Recetas de los últimos 3 meses',
  'Lista de medicamentos actuales',
  'Lista de medicamentos crónicos',
  'Lista de medicamentos con dosis y horarios',
  'Medicamentos que toma habitualmente',
  'Medicamentos de venta libre que consume',
  'Suplementos vitamínicos que consume',
  'Productos naturales o herbolarios que consume',
  'Caja vacía de medicamento actual',
  'Empaque del medicamento',
  'Frasco del medicamento',
  'Frasco del antibiótico actual',
  'Insertos de los medicamentos',
  'Esquema de medicación actual',
  'Esquema de quimioterapia previo',
  'Esquema de inmunoterapia',
  'Receta del especialista previo',
  'Indicaciones de la última consulta',
  'Indicaciones del médico anterior',
  'Indicaciones de la última hospitalización',
  'Suspender aspirina 7 días antes',
  'Suspender clopidogrel 7 días antes',
  'Suspender warfarina según indicación',
  'Suspender anticoagulantes según indicación',
  'Suspender antiinflamatorios 3 días antes',
  'Suspender AINEs 48h antes',
  'Suspender ibuprofeno 48h antes',
  'Suspender metformina 48h antes (estudios con contraste)',
  'Suspender suplementos de hierro 5 días antes',
  'Suspender vitamina E 7 días antes',
  'Suspender ginkgo biloba 7 días antes',
  'Suspender omeprazol según indicación',
  'Suspender estrógenos según indicación',
  'No suspender medicación cardiológica',
  'No suspender antihipertensivos',
  'Continuar con medicación habitual',
  'Continuar con tratamiento de base',
  'Tomar medicación habitual con sorbo de agua',
  'Tomar antihipertensivos con poca agua',
  'Tomar levotiroxina en ayuno',
  'Insulina del paciente',
  'Insulina de rescate',
  'Plumas o jeringas de insulina',
  'Inhalador del paciente',
  'Inhalador de rescate',
  'Cámara espaciadora',
  'Nebulizador',
  'Mascarilla de nebulización',
  'Botiquín personal',
  'Medicamentos para 24 horas (hospitalización)',
  'Lista de alergias medicamentosas',
  'Lista de reacciones adversas previas',
  'Brazalete identificador de alergias',
  'Última orden de retiro de farmacia',
  'Constancia de entrega de medicamentos del seguro',
  'Tarjeta de tratamiento oncológico',
  'Carnet de paciente crónico',
  'Carnet de paciente trasplantado',
  'Carnet de paciente anticoagulado',
  'INR reciente (anticoagulados)',
  'Última nota del oncólogo',
  'Última nota del hematólogo',
  'Última nota del cardiólogo',

  // ===== Acompañantes y transporte (~35) =====
  'Venir acompañado',
  'Acompañante adulto obligatorio',
  'Acompañante mayor de edad',
  'Acompañante para el regreso a casa',
  'Acompañante para post-anestesia',
  'Acompañante para sedación',
  'Acompañante para procedimiento ambulatorio',
  'Acompañante con cédula de identidad',
  'No conducir tras el procedimiento',
  'No conducir las siguientes 24 horas',
  'No conducir hasta nueva indicación',
  'Transporte propio para el regreso',
  'No regresar en transporte público',
  'No regresar manejando',
  'Coordinar transporte privado de regreso',
  'Representante legal del paciente',
  'Representante con poder notariado',
  'Padre o madre obligatorio (menor de edad)',
  'Padre o madre con identificación',
  'Tutor legal del paciente',
  'Tutor con sentencia de tutela',
  'Intérprete (paciente con barrera idiomática)',
  'Intérprete de lengua de señas',
  'Persona de confianza',
  'Cuidador principal del paciente',
  'Cuidador del adulto mayor',
  'Familiar adulto responsable',
  'Acompañante para apoyo emocional',
  'Acompañante para traslado de muestras',
  'Acompañante con vehículo disponible',
  'No traer niños pequeños a la cita',
  'No traer acompañantes adicionales',
  'Solo paciente en sala de espera',
  'Avisar al acompañante quedarse en sala',
  'Coordinar relevos de acompañante',

  // ===== Vestimenta y comodidad (~35) =====
  'Ropa cómoda',
  'Ropa holgada',
  'Ropa fácil de quitar',
  'Ropa abierta por delante',
  'Ropa de dos piezas',
  'Ropa sin cierres ni botones metálicos',
  'Ropa interior de algodón',
  'Sin sostén con aros metálicos',
  'Sin sostén el día del estudio',
  'Sin ropa con apliques metálicos',
  'Sin maquillaje',
  'Sin esmalte de uñas',
  'Sin esmalte de uñas en pies y manos',
  'Sin uñas acrílicas',
  'Sin uñas postizas',
  'Sin pestañas postizas',
  'Sin cremas en la piel',
  'Sin lociones corporales',
  'Sin aceites corporales',
  'Sin perfume',
  'Sin colonia',
  'Sin productos cosméticos en el área',
  'Sin joyería ni accesorios metálicos',
  'Sin aretes metálicos',
  'Sin piercings metálicos',
  'Quitarse anillos antes de venir',
  'Quitarse reloj antes del estudio',
  'Cabello recogido',
  'Cabello sin hebillas metálicas',
  'Toalla personal',
  'Pantuflas',
  'Calzado cómodo',
  'Bata de hospital (si se tiene)',
  'Ropa de cambio',
  'Sandalias o calzado de fácil retiro',

  // ===== Higiene corporal previa (~25) =====
  'Ducha la noche anterior',
  'Ducha la mañana del estudio',
  'Baño completo previo',
  'Lavado del cabello la víspera',
  'Lavado del área genital previo',
  'Asepsia previa al área a evaluar',
  'Sin desodorante',
  'Sin desodorante en axilas (mamografía)',
  'Sin antitranspirante en axilas',
  'Sin talco corporal',
  'Sin polvos en el cuerpo',
  'Sin productos en el cabello',
  'Sin productos en la piel del tórax',
  'Vejiga llena',
  'Vejiga muy llena (ecografía pélvica)',
  'Tomar 1 litro de agua 1h antes',
  'Tomar 4 vasos de agua 30 min antes',
  'No orinar 1h antes del estudio',
  'Vejiga vacía',
  'Orinar antes de la ecografía transvaginal',
  'Lavado intestinal previo',
  'Higiene bucal completa',
  'Cepillado dental antes de la cita',
  'Uso de hilo dental antes de la cita',
  'Sin enjuague bucal con flúor 24h antes',

  // ===== Dieta y restricciones alimentarias (~50) =====
  'Sin café 24h antes',
  'Sin café 48h antes',
  'Sin té negro 24h antes',
  'Sin bebidas con cafeína 24h antes',
  'Sin bebidas energéticas 48h antes',
  'Sin chocolate 24h antes',
  'Sin chocolate 48h antes (estudios de cortisol)',
  'Sin alcohol 24h antes',
  'Sin alcohol 48h antes',
  'Sin alcohol 72h antes',
  'Sin alcohol 5 días antes (perfil hepático)',
  'Sin grasas la noche anterior',
  'Sin frituras 48h antes',
  'Sin comidas pesadas la víspera',
  'Sin lácteos enteros 24h antes',
  'Sin lácteos 48h antes',
  'Sin queso amarillo 48h antes',
  'Dieta blanda 24h antes',
  'Dieta blanda 48h antes',
  'Dieta sin lactosa 48h antes',
  'Dieta sin gluten 72h antes',
  'Dieta baja en sal 48h antes',
  'Dieta baja en yodo 7 días antes',
  'Dieta baja en potasio',
  'Dieta hiposódica',
  'Dieta normal (sin restricción específica)',
  'Dieta habitual del paciente',
  'Sin frutos secos 24h antes',
  'Sin maní 48h antes',
  'Sin nueces 48h antes',
  'Sin condimentos picantes',
  'Sin alimentos picantes 24h antes',
  'Sin cítricos',
  'Sin cítricos 24h antes',
  'Sin jugos cítricos',
  'Sin vitamina C 24h antes',
  'Sin alimentos pigmentados 48h antes',
  'Sin remolacha 48h antes',
  'Sin zanahoria 48h antes',
  'Sin frutas rojas 48h antes',
  'Sin gaseosas 24h antes',
  'Sin refrescos azucarados 24h antes',
  'Sin productos light o dietéticos',
  'Aumentar consumo de agua 48h antes',
  'Hidratación abundante 24h antes',
  'Tomar 2 litros de agua el día previo',
  'Dieta alta en carbohidratos 3 días antes (curva)',
  'Dieta usual sin cambios la víspera',
  'Mantener horarios habituales de comida',
  'No alterar dieta los 3 días previos',

  // ===== Equipo médico personal a traer (~45) =====
  'Monitor de presión arterial personal',
  'Tensiómetro casero',
  'Tensiómetro digital del paciente',
  'Glucómetro y tiras reactivas',
  'Glucómetro del paciente',
  'Lancetas para glucometría',
  'Bitácora de glucemia',
  'Bitácora de glucemia últimos 30 días',
  'Bitácora de glucemia últimos 90 días',
  'Bitácora de presión arterial',
  'Bitácora de presión arterial últimas 2 semanas',
  'Diario de cefaleas',
  'Diario de migrañas',
  'Diario de menstruación',
  'Calendario menstrual',
  'Diario alimenticio 7 días',
  'Diario alimenticio 14 días',
  'Diario de síntomas',
  'Diario de crisis convulsivas',
  'Registro de mareos o vértigos',
  'Aparato de oxigenoterapia personal',
  'Concentrador de oxígeno portátil',
  'Tanque de oxígeno portátil',
  'Cánula nasal del paciente',
  'CPAP personal',
  'BIPAP personal',
  'Máscara de CPAP',
  'Reporte de uso del CPAP',
  'Audífonos del paciente',
  'Audífonos auriculares con baterías',
  'Anteojos del paciente',
  'Anteojos de lectura',
  'Lentes de contacto',
  'Caja de lentes de contacto',
  'Bastón',
  'Andador',
  'Silla de ruedas',
  'Muletas',
  'Cuello cervical',
  'Faja lumbar',
  'Inhaladores actuales',
  'Aerocámara espaciadora',
  'Mascarilla N95',
  'Mascarilla quirúrgica',
  'Protector bucal nocturno',

  // ===== Medidas y registros personales (~35) =====
  'Peso actual registrado',
  'Peso registrado la mañana de la cita',
  'Estatura actualizada',
  'Estatura del último control',
  'Registro de signos vitales últimos 7 días',
  'Registro de signos vitales últimas 2 semanas',
  'Registro de glicemia última semana',
  'Registro de glicemia último mes',
  'Registro de presión arterial última semana',
  'Registro de presión arterial último mes',
  'Promedio de tensión arterial matinal',
  'Promedio de tensión arterial vespertina',
  'Fecha de última menstruación (FUM)',
  'Fecha probable de parto',
  'Calendario menstrual completo',
  'Registro de movimientos fetales',
  'Conteo de movimientos fetales últimas 24h',
  'Registro de líquidos ingeridos',
  'Registro de diuresis 24h',
  'Volumen urinario 24h',
  'Curva de temperatura basal',
  'Curva de temperatura corporal últimos 7 días',
  'Registro de saturación de oxígeno',
  'Registro de saturación últimas 48h',
  'Registro de frecuencia cardíaca',
  'Registro de frecuencia respiratoria',
  'Registro de glucemia capilar pre y post comidas',
  'Perfil glucémico de 7 puntos',
  'Bitácora de cetonas en orina',
  'Bitácora de evacuaciones',
  'Bitácora de patrón intestinal',
  'Curva de crecimiento del niño',
  'Curva ponderal del bebé',
  'Registro de tomas de leche del bebé',
  'Registro de pañales mojados del bebé',

  // ===== Muestras a llevar (~35) =====
  'Muestra de orina recolectada',
  'Muestra de orina en frasco estéril',
  'Primera orina de la mañana',
  'Primera micción del día',
  'Orina de 24 horas',
  'Orina de 24 horas refrigerada',
  'Muestra de heces',
  'Muestra de heces fresca',
  'Muestra de heces en envase limpio',
  'Tres muestras de heces seriadas',
  'Muestra de heces para sangre oculta',
  'Muestra de heces para parásitos',
  'Muestra de esputo',
  'Muestra de esputo matutino',
  'Tres muestras de esputo seriadas',
  'Muestra de esputo BAAR',
  'Muestra de secreción',
  'Muestra de secreción vaginal',
  'Muestra de secreción uretral',
  'Muestra de secreción ótica',
  'Muestra de secreción nasal',
  'Muestra de secreción conjuntival',
  'Muestra de secreción de herida',
  'Muestra de leche materna (cultivo)',
  'Muestra de semen para espermograma',
  'Muestra obtenida tras 3 días de abstinencia',
  'Muestra de cabello para análisis',
  'Muestra de uñas para análisis micológico',
  'Muestra de raspado cutáneo',
  'Muestra de saliva',
  'Hisopado nasofaríngeo previo',
  'Hisopado orofaríngeo previo',
  'Muestra refrigerada hasta entrega',
  'Muestra entregada en menos de 2 horas',
  'Muestra rotulada con nombre y fecha',

  // ===== Misceláneos prácticos (~50) =====
  'Algo de comer post-estudio',
  'Snack para después del estudio',
  'Jugo o golosina para post-extracción sanguínea',
  'Caramelos para subir glicemia post-ayuno',
  'Agua para hidratarse después',
  'Botella de agua personal',
  'Cargador de celular',
  'Power bank',
  'Libro o entretenimiento (espera prolongada)',
  'Revistas o lectura ligera',
  'Audífonos para escuchar música',
  'Tableta o dispositivo para distraerse',
  'Mantita',
  'Abrigo (frío en consultorio)',
  'Suéter ligero',
  'Pañuelos desechables',
  'Pañales para bebé',
  'Pañales talla adecuada',
  'Cambio de ropa para el bebé',
  'Biberón',
  'Biberón con fórmula preparada',
  'Termo con agua tibia',
  'Chupón',
  'Chupete',
  'Mordedor para el bebé',
  'Cobija ligera para el bebé',
  'Silla portabebés',
  'Juguete para distraer al niño',
  'Libro favorito del niño',
  'Snack del niño',
  'Galletas o fruta para el niño',
  'Llegar 15 minutos antes',
  'Llegar 30 minutos antes',
  'Llegar 1 hora antes',
  'Llegar puntual a la hora indicada',
  'Confirmar cita 24h antes',
  'Confirmar cita 48h antes',
  'Reconfirmar cita el día anterior por teléfono',
  'Avisar si tiene síntomas respiratorios al llegar',
  'Avisar si tiene fiebre el día de la cita',
  'Avisar si presenta síntomas COVID',
  'Avisar si tiene síntomas gripales',
  'Notificar si está menstruando',
  'Notificar si tiene heridas abiertas',
  'Notificar embarazo confirmado o sospechado',
  'Notificar lactancia activa',
  'Notificar uso de marcapasos antes del estudio',
  'Notificar implantes metálicos antes del estudio',
  'Notificar prótesis antes del estudio',
  'Notificar alergias al contraste',

  // ===== Estudios cardiológicos y respiratorios específicos (~25) =====
  'No fumar 2h antes del estudio',
  'No fumar 4h antes de la espirometría',
  'No fumar el día del estudio',
  'No realizar ejercicio intenso 24h antes',
  'No realizar ejercicio intenso 12h antes',
  'No usar broncodilatadores 8h antes (espirometría)',
  'No usar broncodilatadores de acción corta 4h antes',
  'No usar broncodilatadores de acción larga 24h antes',
  'No realizar inhalaciones 4h antes',
  'No usar oxígeno suplementario 1h antes (gasometría)',
  'Reposo de 15 minutos antes de la toma de tensión',
  'Reposo de 30 minutos antes del estudio',
  'Reposo absoluto el día previo',
  'No baño caliente antes del estudio cardíaco',
  'No exposición a frío extremo antes del estudio',
  'Sin estrés emocional intenso previo',
  'Sin actividad física intensa 48h antes',
  'Comida ligera 2h antes de la prueba de esfuerzo',
  'Hidratación adecuada antes del estudio',
  'No tomar bebidas frías inmediatamente antes',
  'No realizar Valsalva antes del estudio',
  'Caminar 5 minutos antes de la espirometría',
  'Dormir bien la noche anterior',
  'Sueño reparador mínimo de 6 horas',
  'Evitar trasnochar la noche previa',

  // ===== Preparación quirúrgica y pre-anestésica (~25) =====
  'Evaluación pre-anestésica completa',
  'Evaluación cardiovascular pre-quirúrgica',
  'Riesgo quirúrgico calculado',
  'Consentimiento quirúrgico firmado',
  'Consentimiento anestésico firmado',
  'Rasurado del área quirúrgica (según indicación)',
  'No rasurar el área quirúrgica',
  'Marcado del sitio quirúrgico',
  'Lavado quirúrgico con jabón antiséptico',
  'Baño con clorhexidina la noche anterior',
  'Baño con clorhexidina la mañana de la cirugía',
  'Sin esmalte para oximetría intraoperatoria',
  'Sin prótesis dental el día de la cirugía',
  'Retirar lentes de contacto',
  'Retirar dispositivos auditivos',
  'Retirar prótesis ortopédicas removibles',
  'Vejiga vacía antes de entrar a quirófano',
  'Profilaxis antibiótica según indicación',
  'Profilaxis antitrombótica indicada',
  'Medias antiembólicas',
  'Vendaje compresivo posterior',
  'Acompañante para alta hospitalaria',
  'Coordinar transporte de alta',
  'Disponibilidad de cuidador 24h post-cirugía',
  'Indicaciones post-operatorias por escrito',

  // ===== Estudios oftalmológicos / dermatológicos (~20) =====
  'No usar lentes de contacto 24h antes',
  'No usar lentes de contacto 48h antes',
  'No usar lentes de contacto 7 días antes (cirugía refractiva)',
  'Traer lentes de contacto en su estuche',
  'Traer estuche y solución para lentes',
  'Sin maquillaje en ojos',
  'Sin rímel ni delineador',
  'Sin extensiones de pestañas',
  'Pupilas dilatadas posibles tras estudio',
  'No conducir tras dilatación pupilar',
  'Traer lentes oscuros para después',
  'Acompañante por dilatación pupilar',
  'Sin cremas faciales el día del estudio',
  'Sin tratamientos faciales 7 días antes',
  'Sin exfoliantes 48h antes',
  'Sin exposición solar 2 semanas antes',
  'Sin bronceado artificial 2 semanas antes',
  'Sin maquillaje cubriendo lesiones',
  'Lesiones cutáneas sin tratamiento tópico previo',
  'Suspender tópicos en la zona 7 días antes',

  // ===== Estudios ginecológicos / obstétricos específicos (~25) =====
  'No tener relaciones sexuales 48h antes (citología)',
  'No tener relaciones sexuales 72h antes (espermograma)',
  'Sin duchas vaginales 48h antes',
  'Sin óvulos vaginales 72h antes',
  'Sin cremas vaginales 48h antes',
  'Sin tampones 48h antes',
  'No estar menstruando para el estudio',
  'Coordinar cita fuera del período menstrual',
  'Esperar 5 días post-menstruación',
  'Realizar entre día 8 y 12 del ciclo (histerosalpingografía)',
  'Realizar en primera fase del ciclo',
  'Realizar en fase folicular',
  'Realizar entre día 21 y 23 del ciclo (progesterona)',
  'Coordinar día específico del ciclo',
  'Sin lubricantes vaginales el día del estudio',
  'Sin espermicidas en las 48h previas',
  'Suspender DIU según indicación',
  'Continuar uso de DIU sin cambios',
  'Traer informe de ecografía obstétrica previa',
  'Traer tarjeta de control prenatal',
  'Llevar registro de movimientos fetales',
  'Llevar registro de contracciones',
  'Cronómetro o app para medir contracciones',
  'Bolso de maternidad listo (3er trimestre)',
  'Plan de parto por escrito',

  // ===== Estudios pediátricos específicos (~20) =====
  'Alimentación habitual del niño',
  'Última toma de leche registrada',
  'Última comida del niño anotada',
  'Niño descansado para la consulta',
  'Niño bañado y cambiado',
  'Pañales adicionales del bebé',
  'Toallitas húmedas',
  'Crema para pañalitis',
  'Termómetro pediátrico',
  'Registro de fiebre últimas 72h',
  'Registro de tomas y orina del bebé',
  'Cartilla de seguimiento del crecimiento',
  'Curva de peso del niño',
  'Curva de talla del niño',
  'Esquema de vacunación al día',
  'Hoja de seguimiento del pediatra',
  'Lista de alimentos introducidos',
  'Diario de comportamiento (TDAH/conductual)',
  'Cuaderno de la escuela (evaluación)',
  'Informe del colegio (evaluación pedagógica)',

  // ===== Estudios endocrinológicos específicos (~20) =====
  'Suspender biotina 72h antes (perfil tiroideo)',
  'Suspender suplementos vitamínicos 48h antes',
  'Suspender multivitamínicos 72h antes',
  'No realizar ejercicio 24h antes (cortisol)',
  'Sin estrés intenso 24h antes (cortisol)',
  'Recolección de cortisol matinal a las 8 AM',
  'Recolección de cortisol vespertino a las 4 PM',
  'Saliva para cortisol nocturno',
  'Curva de tolerancia oral a la glucosa 75g',
  'Curva de tolerancia oral a la glucosa 100g',
  'Carga con solución de glucosa estandarizada',
  'No fumar durante la curva de glucosa',
  'Reposo durante toda la curva (3 horas)',
  'No salir del laboratorio durante la curva',
  'Suspender corticoides según indicación',
  'Suspender hormonas tiroideas según indicación',
  'Tomar levotiroxina inmediatamente después de la toma',
  'Suspender anticonceptivos según indicación',
  'Recolección de orina 24h para catecolaminas',
  'Recolección refrigerada con ácido conservante',

  // ===== Indicaciones generales adicionales (~25) =====
  'Llegar con la mayor información posible del cuadro',
  'Anotar todas las preguntas para el médico',
  'Anotar síntomas con fecha de inicio',
  'Anotar síntomas con duración y frecuencia',
  'Anotar factores que mejoran o empeoran',
  'Lista de antecedentes familiares relevantes',
  'Lista de antecedentes personales relevantes',
  'Historia de cirugías previas',
  'Historia de hospitalizaciones previas',
  'Historia de transfusiones previas',
  'Historia de alergias completa',
  'Información de contacto del médico tratante',
  'Información de contacto del especialista',
  'Información de contacto del seguro',
  'Sin obligaciones laborales tras la cita',
  'Bloquear el resto del día tras procedimiento',
  'No agendar otras citas el mismo día',
  'Llegar en ayuno pero hidratado',
  'Tomar todos los estudios en orden cronológico',
  'Llevar estudios en sobre identificado',
  'Llevar carpeta con historia clínica organizada',
  'Llevar lista de teléfonos de emergencia',
  'Confirmar dirección y consultorio antes de salir',
  'Verificar piso y número de consultorio',
  'Llevar dinero en efectivo por si acaso',
];

/**
 * Combina sugerencias del catálogo con las preparaciones frecuentes del
 * doctor (sacadas de su historial). Frecuentes primero, dedupe case-insensitive.
 */
export function mergePreparationSuggestions(
  frequentPreparations: ReadonlyArray<string>,
  catalog: ReadonlyArray<string> = PREPARATION_CATALOG,
): string[] {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const r of frequentPreparations) {
    const key = r.trim().toLowerCase();
    if (key.length === 0 || seen.has(key)) continue;
    seen.add(key);
    result.push(r.trim());
  }

  for (const r of catalog) {
    const key = r.trim().toLowerCase();
    if (key.length === 0 || seen.has(key)) continue;
    seen.add(key);
    result.push(r.trim());
  }

  return result;
}
