-- Database Performance Optimization
-- Created: 2026-02-06
-- Description: Create missing foreign key indexes and drop unused indexes based on Supabase linter analysis.

-- 1. Create Missing Foreign Key Indexes
CREATE INDEX IF NOT EXISTS appointment_status_history_appointment_id_idx ON public.appointment_status_history (appointment_id);
CREATE INDEX IF NOT EXISTS appointments_offline_patient_id_idx ON public.appointments (offline_patient_id);
CREATE INDEX IF NOT EXISTS audit_logs_user_id_idx ON public.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS chat_channels_category_id_idx ON public.chat_channels (category_id);
CREATE INDEX IF NOT EXISTS chat_channels_workspace_id_idx ON public.chat_channels (workspace_id);
CREATE INDEX IF NOT EXISTS chat_message_reads_user_id_idx ON public.chat_message_reads (user_id);
CREATE INDEX IF NOT EXISTS chat_messages_channel_id_idx ON public.chat_messages (channel_id);
CREATE INDEX IF NOT EXISTS chat_messages_reply_to_id_idx ON public.chat_messages (reply_to_id);
CREATE INDEX IF NOT EXISTS chat_messages_sender_id_idx ON public.chat_messages (sender_id);
CREATE INDEX IF NOT EXISTS chat_messages_thread_root_id_idx ON public.chat_messages (thread_root_id);
CREATE INDEX IF NOT EXISTS chat_workspaces_owner_id_idx ON public.chat_workspaces (owner_id);
CREATE INDEX IF NOT EXISTS community_notifications_user_id_idx ON public.community_notifications (user_id);
CREATE INDEX IF NOT EXISTS doctor_offices_doctor_id_idx ON public.doctor_offices (doctor_id);
CREATE INDEX IF NOT EXISTS doctor_reviews_patient_id_idx ON public.doctor_reviews (patient_id);
CREATE INDEX IF NOT EXISTS doctor_schedules_office_id_idx ON public.doctor_schedules (office_id);
CREATE INDEX IF NOT EXISTS doctor_secretaries_secretary_id_idx ON public.doctor_secretaries (secretary_id);
CREATE INDEX IF NOT EXISTS health_goals_paciente_id_idx ON public.health_goals (paciente_id);
CREATE INDEX IF NOT EXISTS measurement_reminders_paciente_id_idx ON public.measurement_reminders (paciente_id);
CREATE INDEX IF NOT EXISTS medication_intake_log_reminder_id_idx ON public.medication_intake_log (reminder_id);
CREATE INDEX IF NOT EXISTS offline_patients_linked_profile_id_idx ON public.offline_patients (linked_profile_id);
CREATE INDEX IF NOT EXISTS phone_verifications_user_id_idx ON public.phone_verifications (user_id);
CREATE INDEX IF NOT EXISTS prescription_watermarks_doctor_id_idx ON public.prescription_watermarks (doctor_id);
CREATE INDEX IF NOT EXISTS specialty_consultation_reasons_specialty_id_idx ON public.specialty_consultation_reasons (specialty_id);
CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx ON public.user_sessions (user_id);
CREATE INDEX IF NOT EXISTS verificaciones_sacs_user_id_idx ON public.verificaciones_sacs (user_id);

-- 2. Drop Unused Indexes
DROP INDEX IF EXISTS idx_academy_modules_created_by;
DROP INDEX IF EXISTS idx_academy_progress_module_id;
DROP INDEX IF EXISTS idx_appointment_status_history_changed_by;
DROP INDEX IF EXISTS idx_appointments_cancelled_by;
DROP INDEX IF EXISTS idx_appointments_location_id;
DROP INDEX IF EXISTS idx_appointments_medical_record_id;
DROP INDEX IF EXISTS idx_chat_messages_deleted_by;
DROP INDEX IF EXISTS idx_chat_typing_indicators_user_id;
DROP INDEX IF EXISTS idx_chat_user_presence_current_channel_id;
DROP INDEX IF EXISTS idx_community_notifications_actor_id;
DROP INDEX IF EXISTS idx_conversations_appointment_id;
DROP INDEX IF EXISTS idx_deletion_requests_user_id;
DROP INDEX IF EXISTS idx_doctor_details_verified_by;
DROP INDEX IF EXISTS idx_doctor_documents_verified_by;
DROP INDEX IF EXISTS idx_doctor_notifications_doctor_id;
DROP INDEX IF EXISTS idx_doctor_patients_patient_id;
DROP INDEX IF EXISTS idx_doctor_preferences_current_office_id;
DROP INDEX IF EXISTS idx_doctor_quick_actions_doctor_id;
DROP INDEX IF EXISTS idx_doctor_recipe_settings_office_id;
DROP INDEX IF EXISTS idx_doctor_reviews_appointment_id;
DROP INDEX IF EXISTS idx_doctor_secretaries_invited_by;
DROP INDEX IF EXISTS idx_doctor_settings_active_frame_id;
DROP INDEX IF EXISTS idx_doctor_settings_active_watermark_id;
DROP INDEX IF EXISTS idx_doctor_tasks_doctor_id;
DROP INDEX IF EXISTS idx_doctor_themes_doctor_id;
DROP INDEX IF EXISTS idx_doctor_verifications_cache_verified_by;
DROP INDEX IF EXISTS idx_health_metrics_appointment_id;
DROP INDEX IF EXISTS idx_health_metrics_medical_record_id;
DROP INDEX IF EXISTS idx_lab_order_status_history_cambiado_por;
DROP INDEX IF EXISTS idx_lab_order_status_history_order_id;
DROP INDEX IF EXISTS idx_lab_order_tests_order_id;
DROP INDEX IF EXISTS idx_lab_order_tests_test_type_id;
DROP INDEX IF EXISTS idx_lab_orders_appointment_id;
DROP INDEX IF EXISTS idx_lab_orders_laboratorio_id;
DROP INDEX IF EXISTS idx_lab_orders_medical_record_id;
DROP INDEX IF EXISTS idx_lab_orders_medico_id;
DROP INDEX IF EXISTS idx_lab_result_values_result_id;
DROP INDEX IF EXISTS idx_lab_results_order_id;
DROP INDEX IF EXISTS idx_lab_results_test_type_id;
DROP INDEX IF EXISTS idx_lab_results_validado_por;
DROP INDEX IF EXISTS idx_medical_notes_appointment_id;
DROP INDEX IF EXISTS idx_medical_notes_doctor_id;
DROP INDEX IF EXISTS idx_medical_notes_patient_id;
DROP INDEX IF EXISTS idx_medical_records_appointment_id;
DROP INDEX IF EXISTS idx_medical_records_offline_patient_id;
DROP INDEX IF EXISTS idx_user_modules_user_id;
DROP INDEX IF EXISTS idx_user_modules_enabled;
DROP INDEX IF EXISTS idx_medication_intake_log_paciente_id;
DROP INDEX IF EXISTS idx_medication_reminders_prescription_medication_id;
DROP INDEX IF EXISTS idx_office_photos_office_id;
DROP INDEX IF EXISTS idx_patient_documents_verified_by;
DROP INDEX IF EXISTS idx_prescription_medications_medication_id;
DROP INDEX IF EXISTS idx_prescriptions_appointment_id;
DROP INDEX IF EXISTS idx_prescriptions_farmacia_id;
DROP INDEX IF EXISTS idx_patient_documents_status;
DROP INDEX IF EXISTS idx_prescriptions_medical_record_id;
DROP INDEX IF EXISTS idx_qa_answer_comments_author_id;
DROP INDEX IF EXISTS idx_support_messages_sender_id;
DROP INDEX IF EXISTS idx_support_messages_ticket_id;
DROP INDEX IF EXISTS idx_support_tickets_assigned_to;
DROP INDEX IF EXISTS idx_support_tickets_created_by;
DROP INDEX IF EXISTS idx_transactions_payment_method_id;
DROP INDEX IF EXISTS idx_chat_typing_expiration;
DROP INDEX IF EXISTS idx_agora_sessions_initiator;
DROP INDEX IF EXISTS idx_agora_sessions_recipient;
DROP INDEX IF EXISTS idx_agora_sessions_status;
DROP INDEX IF EXISTS idx_agora_sessions_type;
DROP INDEX IF EXISTS idx_agora_sessions_started_at;
DROP INDEX IF EXISTS idx_agora_sessions_participants;
DROP INDEX IF EXISTS idx_agora_sessions_active_participants;
DROP INDEX IF EXISTS idx_agora_sessions_conversation;
DROP INDEX IF EXISTS idx_agora_sessions_appointment;
DROP INDEX IF EXISTS idx_chat_channels_last_message;
DROP INDEX IF EXISTS idx_chat_presence_expires;
DROP INDEX IF EXISTS idx_chat_participants_unread;
DROP INDEX IF EXISTS idx_chat_participants_channel;
DROP INDEX IF EXISTS idx_chat_participants_user;
DROP INDEX IF EXISTS idx_chat_participants_presence;
DROP INDEX IF EXISTS idx_doctor_details_subespecialties;
DROP INDEX IF EXISTS idx_appointments_enviar_recordatorio;
DROP INDEX IF EXISTS idx_doctor_reviews_doctor_id;
DROP INDEX IF EXISTS idx_appointments_metodo_pago;
DROP INDEX IF EXISTS idx_doctor_details_specialty;
DROP INDEX IF EXISTS idx_doctor_details_verified;
DROP INDEX IF EXISTS idx_doctor_details_featured;
DROP INDEX IF EXISTS idx_doctor_details_rating;
DROP INDEX IF EXISTS idx_doctor_availability_exceptions_doctor_id;
